<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1 (Python 3.9.6 on win32)" generated="20210721 10:57:51.279" rpa="false" schemaversion="2">
<suite id="s1" name="Tests" source="C:\Users\m.salaun\Documents\Curl-testing\tests.rst">
<test id="s1-t1" name="User requests a web page">
<kw name="Request Page From Url">
<arg>https://klmp200.net/</arg>
<msg timestamp="20210721 10:57:51.385" level="FAIL">No keyword with name 'Request Page From Url' found.</msg>
<status status="FAIL" starttime="20210721 10:57:51.385" endtime="20210721 10:57:51.386"/>
</kw>
<kw name="Web Page Should Be Like">
<arg>klmp200.html</arg>
<status status="NOT RUN" starttime="20210721 10:57:51.387" endtime="20210721 10:57:51.387"/>
</kw>
<status status="FAIL" starttime="20210721 10:57:51.384" endtime="20210721 10:57:51.388">No keyword with name 'Request Page From Url' found.</status>
</test>
<status status="FAIL" starttime="20210721 10:57:51.279" endtime="20210721 10:57:51.390"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Tests">Tests</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210721 10:57:51.379" level="ERROR">Error in file 'C:\Users\m.salaun\Documents\Curl-testing\tests.rst' on line 2: Initializing library 'MyCurlLibrary' with no arguments failed: AttributeError: module 'os' has no attribute 'join'
Traceback (most recent call last):
  File "C:\Users\m.salaun\Documents\Curl-testing\library\MyCurlLibrary.py", line 14, in __init__
    self._site_dir = os.join(self._current_dir, "site")</msg>
</errors>
</robot>
